Repository laminas/laminas-inputfilter, pull requests merged in 2022-07, with the labels that each got.

#62 Adjusted tests so that stubbed `ContainerInterface#has()` returns `bool` instead of `null`
  test/InputFilterPluginManagerFactoryTest.php
Labels: Bug

#66 Remove dependency on prophecy
  composer.json
  composer.lock
  psalm-baseline.xml
  test/FactoryTest.php
  test/FileInput/PsrFileInputDecoratorTest.php
  test/FileInput/TestAsset/InitializableInputFilterInterface.php
  test/InputFilterAbstractServiceFactoryTest.php
  test/InputFilterPluginManagerFactoryTest.php
  test/InputFilterPluginManagerTest.php
  test/InputTest.php
  test/ModuleTest.php
Labels: Enhancement

#67 Apply PHP 7.4 syntax and typed property
  phpcs.xml.dist
  psalm-baseline.xml
  src/CollectionInputFilter.php
  src/FileInput.php
  src/FileInput/HttpServerFileInputDecorator.php
  src/FileInput/PsrFileInputDecorator.php
  test/ArrayInputTest.php
  test/BaseInputFilterTest.php
  test/CollectionInputFilterTest.php
  test/FileInput/HttpServerFileInputDecoratorTest.php
  test/FileInput/PsrFileInputDecoratorTest.php
  test/InputFilterAbstractServiceFactoryTest.php
  test/InputTest.php
  test/ModuleTest.php
  test/OptionalInputFilterTest.php
Labels: Enhancement

#60 Regression for input filter collections
  psalm-baseline.xml
  src/BaseInputFilter.php
  test/ValidationGroup/InputFilterCollectionsValidationGroupTest.php
  test/ValidationGroup/InputFilterStringValidationGroupTest.php
Labels: BC Break, Bug
