Repository laminas/laminas-inputfilter, pull requests merged in 2025-08, with the labels that each got.

#147 Replace ConfigProvider deprecated type reference
  src/ConfigProvider.php
  test/ConfigProviderTest.php
Labels: BC Break, QA

#148 Remove use of deprecated NotEmpty->getOption
  test/ArrayInputTest.php
  test/CollectionInputFilterTest.php
  test/FileInput/FileInputTest.php
  test/InputTest.php
Labels: QA

#151 Refactor `Factory::createInput()`
  psalm-baseline.xml
  psalm.xml.dist
  src/BaseInputFilter.php
  src/ConfigProvider.php
  src/Factory.php
  src/Input.php
  src/InputFilter.php
  src/InputFilterInterface.php
  src/InputInterface.php
  test/BaseInputFilterTest.php
  test/CollectionInputFilterTest.php
  test/ConfigProviderTest.php
  test/FactoryTest.php
  test/InputFilterPluginManagerTest.php
  test/InputFilterTest.php
  test/StaticAnalysis/AddingInputsWithArraySpecs.php
  test/TestHelper.php
Labels: BC Break, Enhancement, QA
